### PR TITLE
Fix some haddock warnings

### PR DESCRIPTION
**Pull request by Bodigrim**

### CODE REVIEW

**Comment by andreasabel** [comment]
@Bodigrim : Can you link to some rendering of the haddocks?  (I guess the easiest way to get a rendering is to make a hackage release candidate.)

**Comment by Bodigrim** [comment]
@andreasabel would haddock log be sufficient to explain the difference?

Before:
```
Running Haddock on library for tasty-1.4.2.3..
 100% ( 17 / 17) in 'Test.Tasty.Options'
   0% (  0 /  2) in 'Test.Tasty.Patterns.Types'
  Missing documentation for:
    Module header
    Expr (Test/Tasty/Patterns/Types.hs:7)
  50% (  1 /  2) in 'Test.Tasty.Patterns.Printer'
  Missing documentation for:
    Module header
  83% (  5 /  6) in 'Test.Tasty.Patterns.Parser'
  Missing documentation for:
    ParseResult (Test/Tasty/Patterns/Parser.hs:31)
  40% (  2 /  5) in 'Test.Tasty.Patterns.Eval'
  Missing documentation for:
    Module header
    Path (Test/Tasty/Patterns/Eval.hs:19)
    asB (Test/Tasty/Patterns/Eval.hs:71)
Warning: 'TestReporter' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
Warning: 'ingredientOptions' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
 100% ( 10 / 10) in 'Test.Tasty.Providers.ConsoleFormat'
Warning: 'testCase' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
Warning: 'DependencyLoop' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
 100% ( 10 / 10) in 'Test.Tasty.Providers'
Warning: 'tryIngredients' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
Warning: 'ingredientOption' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
 100% (  7 /  7) in 'Test.Tasty.Ingredients'
Warning: 'askOption' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
Warning: 'TestOuput' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
Warning: 'localOption' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
 100% ( 21 / 21) in 'Test.Tasty.Ingredients.ConsoleReporter'
Warning: 'tasty' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
 100% ( 12 / 12) in 'Test.Tasty.Ingredients.Basic'
Warning: 'defaultMain' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
Warning: 'askOption' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
Warning: 'defaultIngredients' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
  87% ( 50 / 57) in 'Test.Tasty.Runners'
  Missing documentation for:
    TestPattern (Test/Tasty/Patterns.hs:27)
    parseExpr (Test/Tasty/Patterns.hs:40)
    parseTestPattern (Test/Tasty/Patterns.hs:46)
    noPattern (Test/Tasty/Patterns.hs:30)
    Path (Test/Tasty/Patterns/Eval.hs:19)
    exprMatches (Test/Tasty/Patterns.hs:51)
    testPatternMatches (Test/Tasty/Patterns.hs:57)
Warning: 'exitWith' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
 100% ( 25 / 25) in 'Test.Tasty'
Warning: Test.Tasty.Patterns.Parser: could not find link destinations for:

  - Test.Tasty.Patterns.Parser.expr2
  - Test.Tasty.Patterns.Expr.makeExprParser
Warning: Test.Tasty.Patterns.Eval: could not find link destinations for:

  - Test.Tasty.Patterns.Eval.M
  - Test.Tasty.Patterns.Eval.Value
Running Haddock on library for tasty-hunit-0.10.0.2..
Running Haddock on library for tasty-smallcheck-0.8.2..
Running Haddock on library for tasty-quickcheck-0.10.2..
Warning: 'TestCase' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
Warning: 'Test' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
Warning: 'Testable' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
 100% ( 24 / 24) in 'Test.Tasty.HUnit'
Warning: 'Test' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
 100% ( 15 / 15) in 'Test.Tasty.SmallCheck'
Warning: 'Test' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
  96% (182 /189) in 'Test.Tasty.QuickCheck'
  Missing documentation for:
    QuickCheckReplay (Test/Tasty/QuickCheck.hs:80)
    ShrinkState
    shrink2
    arbitrary2
    shrink1
    arbitrary1
    QC (Test/Tasty/QuickCheck.hs:61)
Warning: Test.Tasty.QuickCheck: could not find link destinations for:

  - Test.QuickCheck.Exception.AnException
  - Test.QuickCheck.Random.QCGen
  - Test.QuickCheck.Property.Prop
  - Test.QuickCheck.Property.Result
  - Test.QuickCheck.Function.Shrunk
  - Test.QuickCheck.Modifiers.InfiniteListInternalData
  - Test.QuickCheck.Arbitrary.GCoArbitrary
```

After:
```
Running Haddock on library for tasty-1.4.2.3..
 100% ( 17 / 17) in 'Test.Tasty.Options'
   0% (  0 /  2) in 'Test.Tasty.Patterns.Types'
  Missing documentation for:
    Module header
    Expr (Test/Tasty/Patterns/Types.hs:7)
  50% (  1 /  2) in 'Test.Tasty.Patterns.Printer'
  Missing documentation for:
    Module header
  83% (  5 /  6) in 'Test.Tasty.Patterns.Parser'
  Missing documentation for:
    ParseResult (Test/Tasty/Patterns/Parser.hs:31)
  40% (  2 /  5) in 'Test.Tasty.Patterns.Eval'
  Missing documentation for:
    Module header
    Path (Test/Tasty/Patterns/Eval.hs:19)
    asB (Test/Tasty/Patterns/Eval.hs:71)
 100% ( 10 / 10) in 'Test.Tasty.Providers.ConsoleFormat'
 100% ( 10 / 10) in 'Test.Tasty.Providers'
 100% (  7 /  7) in 'Test.Tasty.Ingredients'
 100% ( 21 / 21) in 'Test.Tasty.Ingredients.ConsoleReporter'
 100% ( 12 / 12) in 'Test.Tasty.Ingredients.Basic'
  87% ( 50 / 57) in 'Test.Tasty.Runners'
  Missing documentation for:
    TestPattern (Test/Tasty/Patterns.hs:27)
    parseExpr (Test/Tasty/Patterns.hs:40)
    parseTestPattern (Test/Tasty/Patterns.hs:46)
    noPattern (Test/Tasty/Patterns.hs:30)
    Path (Test/Tasty/Patterns/Eval.hs:19)
    exprMatches (Test/Tasty/Patterns.hs:51)
    testPatternMatches (Test/Tasty/Patterns.hs:57)
 100% ( 25 / 25) in 'Test.Tasty'
Warning: Test.Tasty.Patterns.Eval: could not find link destinations for:

  - Test.Tasty.Patterns.Eval.M
  - Test.Tasty.Patterns.Eval.Value
Running Haddock on library for tasty-quickcheck-0.10.2..
Running Haddock on library for tasty-hunit-0.10.0.2..
Running Haddock on library for tasty-smallcheck-0.8.2..
 100% ( 24 / 24) in 'Test.Tasty.HUnit'
 100% ( 15 / 15) in 'Test.Tasty.SmallCheck'
  96% (182 /189) in 'Test.Tasty.QuickCheck'
  Missing documentation for:
    QuickCheckReplay (Test/Tasty/QuickCheck.hs:80)
    ShrinkState
    shrink2
    arbitrary2
    shrink1
    arbitrary1
    QC (Test/Tasty/QuickCheck.hs:61)
Warning: Test.Tasty.QuickCheck: could not find link destinations for:

  - Test.QuickCheck.Exception.AnException
  - Test.QuickCheck.Random.QCGen
  - Test.QuickCheck.Property.Prop
  - Test.QuickCheck.Property.Result
  - Test.QuickCheck.Function.Shrunk
  - Test.QuickCheck.Modifiers.InfiniteListInternalData
  - Test.QuickCheck.Arbitrary.GCoArbitrary
```

**Review by andreasabel — APPROVED** [review]
Thanks!

**Comment by andreasabel** [comment]
> @andreasabel would haddock log be sufficient to explain the difference?

Na, I meant to look at the rendering to check formatting, clickability etc.
But don't bother.  I looked through the changes and it is mostly correcting uses of `'...'`, and it looks fine.

**Pull request merged**
