### PR TITLE
Avoid blanket import from `GHC.Conc`

### PR DESCRIPTION
**Pull request by edsko**
Corresponding ticket for `async` itself at https://github.com/simonmar/async/pull/153.

### CODE REVIEW

**Comment by Bodigrim** [comment]
@amesgen if you get a moment to fix WASM CI job, it would be most appreciated. (I assume it's just a hash change, but cannot verify AFK)

**Comment by Bodigrim** [comment]
@edsko could you please rebase?

Any particular motivation for this change? Why `GHC.Conc` only?

**Comment by edsko** [comment]
@Bodigrim Have rebased. As for motivation: `GHC.Conc` exports some stuff that `Control.Concurrent.STM` also exports, which leads to name clashes when using a version of `stm` that doesn't straight up re-export stuff from `GHC.Conc` but does something slightly different (such as specifically https://github.com/edsko/stm-debug).

**Comment by Bodigrim** [comment]
Thanks!

**Pull request merged**
