### PR TITLE
Support mtl-2.3-rc3

### PR DESCRIPTION
**Pull request by Bodigrim**
See https://discourse.haskell.org/t/ann-release-candidate-for-mtl-2-3/3687

### CODE REVIEW

**Comment by UnkindPartition** [comment]
Sorry, missed the notification on this one.

**Comment by sjakobi** [comment]
mtl-2.3 is finally out. Could you please make a release?

I noticed that the latest `tasty` release is broken when building with `mtl-2.3`. As a Hackage trustee, I'll try to take care of restricting the bounds.

**Comment by sjakobi** [comment]
> I noticed that the latest `tasty` release is broken when building with `mtl-2.3`. As a Hackage trustee, I'll try to take care of restricting the bounds.

Done: https://hackage.haskell.org/package/tasty-1.4.2.1/revisions/

**Comment by andreasabel** [comment]
> mtl-2.3 is finally out. Could you please make a release?

Lifted to:
- #333

**Pull request merged**
