### PR TITLE
Bump core to 1.4.2.2; CHANGELOG

### PR DESCRIPTION
**Pull request by andreasabel**
Release 1.4.2.2, closing #333.

Oops, just realized that I am not an uploader for this package on hackage.  
One of them, please get in contact, or pick up this PR:
- @ekmett
- @ocharles
- @UnkindPartition
- @bergey

### CODE REVIEW

**Comment by Bodigrim** [comment]
Let's drop `mtl` dependency altogether: naked `transformers` are entirely sufficient for the purposes of `tasty`.

**Comment by Bodigrim** [comment]
> Let's drop `mtl` dependency altogether: naked `transformers` are entirely sufficient for the purposes of `tasty`.

This would also enable `mtl` itself to have a test suite ;)
Cf. https://github.com/haskell/mtl/issues/117#issuecomment-1120492816

**Comment by andreasabel** [comment]
> Let's drop `mtl` dependency altogether: naked `transformers` are entirely sufficient for the purposes of `tasty`.

Definitely, if `mtl` isn't needed.

However, this need not stop us releasing a patch for `mtl-2.3` first.  It is release-ready.

**Comment by andreasabel** [comment]
@Bodigrim : Suppose I get the uploader rights soon, would you think it makes sense to release this PR first or simply directly #335 ?  Since you are already done with the work removing the `mtl` dependency...

**Comment by andreasabel** [comment]
I put this PR as candidate up: https://hackage.haskell.org/package/tasty-1.4.2.2/candidate

**Comment by andreasabel** [comment]
Published: https://hackage.haskell.org/package/tasty-1.4.2.2

**Pull request merged**
